PATCH /api/0.12/tenders/84e8f22de92342728058e0c00c862e6c/bids/5e0336b3fe7d44338e6a887ded76d80c?acc_token=e3005f793fca4f9697135b887c4d4397 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "85b97a197135438598ee0c9f9360c0e6", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2016-03-08T16:32:17.257128+02:00", 
    "status": "pending", 
    "id": "5e0336b3fe7d44338e6a887ded76d80c", 
    "lotValues": [
      {
        "relatedLot": "85b97a197135438598ee0c9f9360c0e6", 
        "date": "2016-03-08T16:32:17.257864+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

