PATCH /api/0.12/tenders/84e8f22de92342728058e0c00c862e6c?acc_token=8da395b923954694bb73cc73e7a67d0b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2016-02-07T16:32:18.298293+02:00", 
      "endDate": "2016-03-04T16:32:18.298293+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2016-02-07T16:32:18.298293+02:00", 
      "endDate": "2016-02-27T16:32:18.298293+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-18T16:32:19.487589+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "84e8f22de92342728058e0c00c862e6c", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2016-03-18T16:32:19.487589+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "85b97a197135438598ee0c9f9360c0e6"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "a4960852dcdf47b0a414e9ebc5b35211"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2016-03-08T16:32:18.631092+02:00", 
      "endDate": "2016-03-18T16:32:19.487589+02:00"
    }, 
    "tenderID": "UA-2016-03-08-000001", 
    "dateModified": "2016-03-08T16:32:19.494036+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2016-02-07T16:32:18.298293+02:00", 
      "endDate": "2016-03-08T16:32:18.298293+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "85b97a197135438598ee0c9f9360c0e6", 
        "id": "71b4cb75162946c5b18790ddaad9fca6", 
        "bidID": "5e0336b3fe7d44338e6a887ded76d80c"
      }, 
      {
        "status": "active", 
        "lotID": "85b97a197135438598ee0c9f9360c0e6", 
        "id": "5bea1da27499482a88f0b58957a2907e", 
        "bidID": "1ba4b0f8d35948708c64be179ec40978"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "85b97a197135438598ee0c9f9360c0e6", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "be36ae961e1046948e627bca2387c617", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "a4960852dcdf47b0a414e9ebc5b35211", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "0b2e496e3daf42e5927a96cab73070cf", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "5e0336b3fe7d44338e6a887ded76d80c"
      }, 
      {
        "status": "pending", 
        "id": "1ba4b0f8d35948708c64be179ec40978"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

