POST /api/0.12/tenders/84e8f22de92342728058e0c00c862e6c/lots?acc_token=8da395b923954694bb73cc73e7a67d0b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 214
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/84e8f22de92342728058e0c00c862e6c/lots/85b97a197135438598ee0c9f9360c0e6
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "85b97a197135438598ee0c9f9360c0e6"
  }
}

