PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/questions/0122de48e04b446ea31fa6730576e595?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-03-08T16:32:05.549235+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "0122de48e04b446ea31fa6730576e595", 
    "questionOf": "tender"
  }
}

