PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/qualifications/c4f8369a8b5b437ebeaa41e50cb7b559?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "id": "c4f8369a8b5b437ebeaa41e50cb7b559", 
    "bidID": "04cdf298020a4852a67b250d3e04290e"
  }
}

