PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/qualifications/24fb5abe7bf74b9c8199bcc80cab76c5?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "id": "24fb5abe7bf74b9c8199bcc80cab76c5", 
    "bidID": "1c5d010e40254c1dbb4aeef5c327597f"
  }
}

