GET /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2016-01-27T16:31:47.529151+02:00", 
      "endDate": "2016-02-23T16:31:47.529151+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/af13521637c74f7aaf9f1d52782e99f1", 
    "enquiryPeriod": {
      "startDate": "2016-01-27T16:31:47.529151+02:00", 
      "endDate": "2016-02-17T16:31:47.529151+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "id": "c4f8369a8b5b437ebeaa41e50cb7b559", 
        "bidID": "04cdf298020a4852a67b250d3e04290e"
      }, 
      {
        "status": "active", 
        "id": "24fb5abe7bf74b9c8199bcc80cab76c5", 
        "bidID": "1c5d010e40254c1dbb4aeef5c327597f"
      }, 
      {
        "status": "unsuccessful", 
        "id": "343d5c04f88c464f8ce0528f642f9804", 
        "bidID": "caaadfdb938c442bb67ab289363e6590"
      }
    ], 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-08T17:07:47.529151+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-03-08T16:32:05.549235+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "0122de48e04b446ea31fa6730576e595", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "af13521637c74f7aaf9f1d52782e99f1", 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/3b95ac5554904720bed2c4fcae434d4f?download=27c6335f49434b728393acc285547a70", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:04.858556+02:00", 
        "id": "3b95ac5554904720bed2c4fcae434d4f", 
        "dateModified": "2016-03-08T16:32:04.858583+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?download=c9d88db99380423aa68ad940bbe5c824", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:05.104009+02:00", 
        "id": "797ecc3074424c8685a11c54ef8f27ad", 
        "dateModified": "2016-03-08T16:32:05.104049+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?download=ccc241fe427148c8839683f7fb6a42d3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:05.104009+02:00", 
        "id": "797ecc3074424c8685a11c54ef8f27ad", 
        "dateModified": "2016-03-08T16:32:05.350993+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2016-02-27T16:31:47.529151+02:00", 
      "endDate": "2016-03-08T16:31:47.529151+02:00"
    }, 
    "tenderID": "UA-2016-03-08-000001", 
    "dateModified": "2016-03-08T16:32:11.944173+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2016-01-27T16:31:47.529151+02:00", 
      "endDate": "2016-02-27T16:31:47.529151+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-03-08T16:31:47.529151+02:00", 
      "shouldStartAfter": "2016-03-08T16:31:47.529151+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "06affbb4b90e482fb3163dcca47255be", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "78d669fde4a041228b824c2151085d2a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/d164ed37c7cb43e2892e5f0b9dd41447?download=9f3440ee641748eda6c459af17446ea8", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-03-08T16:32:06.762571+02:00", 
            "id": "d164ed37c7cb43e2892e5f0b9dd41447", 
            "dateModified": "2016-03-08T16:32:06.762611+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/6bd8cc2dcbcc4e8d8e4bfb6a15b647a8?download=58731732002348838d9878fc768a22b3", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-03-08T16:32:07.011993+02:00", 
            "id": "6bd8cc2dcbcc4e8d8e4bfb6a15b647a8", 
            "dateModified": "2016-03-08T16:32:07.012031+02:00"
          }
        ], 
        "id": "04cdf298020a4852a67b250d3e04290e"
      }, 
      {
        "status": "active", 
        "id": "1c5d010e40254c1dbb4aeef5c327597f"
      }, 
      {
        "status": "unsuccessful", 
        "id": "caaadfdb938c442bb67ab289363e6590"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

