GET /api/0.12/tenders/808dc0f4fe5144b3a8b50ad7003cecdb/awards/fdbfea8b3f884caaad5f3c0cfcc0eaf3/complaints/f24a7844adac4042af19e8434df953d8 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-03-08T16:31:54.884269+02:00", 
    "tendererActionDate": "2016-03-08T16:31:55.436733+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "f24a7844adac4042af19e8434df953d8", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2016-03-08T16:31:52.784110+02:00", 
    "complaintID": "UA-2016-03-08-000001.1", 
    "date": "2016-03-08T16:31:52.106832+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/808dc0f4fe5144b3a8b50ad7003cecdb/awards/fdbfea8b3f884caaad5f3c0cfcc0eaf3/complaints/f24a7844adac4042af19e8434df953d8/documents/e429bbf5066c47bfa06e0c0618544552?download=630d9c375635430f917b3c729e11f9c9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:31:52.492982+02:00", 
        "id": "e429bbf5066c47bfa06e0c0618544552", 
        "dateModified": "2016-03-08T16:31:52.493023+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/808dc0f4fe5144b3a8b50ad7003cecdb/awards/fdbfea8b3f884caaad5f3c0cfcc0eaf3/complaints/f24a7844adac4042af19e8434df953d8/documents/218d767f91814478a33dd3450169703b?download=e38f5ea8b6ef48adaadca6ab3820d8a2", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:31:54.592409+02:00", 
        "id": "218d767f91814478a33dd3450169703b", 
        "dateModified": "2016-03-08T16:31:54.592448+02:00"
      }
    ], 
    "dateAccepted": "2016-03-08T16:31:53.944433+02:00"
  }
}

