GET /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/1c5d010e40254c1dbb4aeef5c327597f?acc_token=50a748e906464435b930b71171bdae09 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-03-08T16:32:09.169637+02:00", 
    "id": "1c5d010e40254c1dbb4aeef5c327597f", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/af13521637c74f7aaf9f1d52782e99f1?key_for_bid=1c5d010e40254c1dbb4aeef5c327597f"
  }
}

