PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e?acc_token=9f5d35b846f1459ba3ad4e4ea1535393 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/d164ed37c7cb43e2892e5f0b9dd41447?download=9f3440ee641748eda6c459af17446ea8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:06.762571+02:00", 
        "id": "d164ed37c7cb43e2892e5f0b9dd41447", 
        "dateModified": "2016-03-08T16:32:06.762611+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/6bd8cc2dcbcc4e8d8e4bfb6a15b647a8?download=58731732002348838d9878fc768a22b3", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:07.011993+02:00", 
        "id": "6bd8cc2dcbcc4e8d8e4bfb6a15b647a8", 
        "dateModified": "2016-03-08T16:32:07.012031+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/eligibility_documents/ef3368c54f2449e08886b58e7745c0f3?download=3873c167076f4d00b6b81a154a6bc588", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:08.057514+02:00", 
        "id": "ef3368c54f2449e08886b58e7745c0f3", 
        "dateModified": "2016-03-08T16:32:08.057551+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "04cdf298020a4852a67b250d3e04290e", 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/financial_documents/1b0058943046468daa372412bcf0a28c?download=8575a633363b4444b1c3d9365761a4af", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:07.482386+02:00", 
        "id": "1b0058943046468daa372412bcf0a28c", 
        "dateModified": "2016-03-08T16:32:07.482423+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/financial_documents/85172483ec3a482fb1fc39307bf4d902?download=211c3b200cf34c31ace541f4eb4598a3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:07.727065+02:00", 
        "id": "85172483ec3a482fb1fc39307bf4d902", 
        "dateModified": "2016-03-08T16:32:07.727104+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-03-08T16:32:06.530810+02:00", 
    "qualificationDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/qualification_documents/3a0585319a17405882cf92d9f9a96bd1?download=343fab6d83684f8ea407e82dfa89ee40", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:08.288802+02:00", 
        "id": "3a0585319a17405882cf92d9f9a96bd1", 
        "dateModified": "2016-03-08T16:32:08.288851+02:00"
      }
    ]
  }
}

