PATCH /api/0.12/tenders/71c01769c95048878c7b49d4c6f5d328/complaints/4b72dbe35fe7412b9fd6ca806f8e33ee?acc_token=f858bac0d3b54451990fc090dac18dbc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/71c01769c95048878c7b49d4c6f5d328/complaints/4b72dbe35fe7412b9fd6ca806f8e33ee/documents/6ebe74f66c7246a08e5d208f52e6279e?download=07448f2890a94bff9daf80fffb862dc0", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:31:58.211087+02:00", 
        "id": "6ebe74f66c7246a08e5d208f52e6279e", 
        "dateModified": "2016-03-08T16:31:58.211125+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2016-03-08T16:31:59.336824+02:00", 
    "complaintID": "UA-2016-03-08-000001.1", 
    "date": "2016-03-08T16:31:57.999854+02:00", 
    "type": "complaint", 
    "id": "4b72dbe35fe7412b9fd6ca806f8e33ee"
  }
}

