PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/6bd8cc2dcbcc4e8d8e4bfb6a15b647a8?acc_token=9f5d35b846f1459ba3ad4e4ea1535393 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/bids/04cdf298020a4852a67b250d3e04290e/documents/6bd8cc2dcbcc4e8d8e4bfb6a15b647a8?download=58731732002348838d9878fc768a22b3", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-08T16:32:07.011993+02:00", 
    "id": "6bd8cc2dcbcc4e8d8e4bfb6a15b647a8", 
    "dateModified": "2016-03-08T16:32:07.012031+02:00"
  }
}

