POST /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/cancellations?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/cancellations/5c3a7812983b49b7b401bd4478f7a1b1
{
  "data": {
    "date": "2016-03-08T16:32:13.171046+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "5c3a7812983b49b7b401bd4478f7a1b1"
  }
}

