GET /api/0.12/tenders/ea5d68674ac847f887792dc42191b192/qualifications/c0e7730a0b884d2797db310ea4b88083/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2016-03-08T16:32:25.589270+02:00", 
      "tendererActionDate": "2016-03-08T16:32:26.106622+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "699f247a7b8b4016abd9d4b75e44b7fd", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2016-03-08T16:32:23.426559+02:00", 
      "complaintID": "UA-2016-03-08-000001.1", 
      "date": "2016-03-08T16:32:22.803938+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/ea5d68674ac847f887792dc42191b192/qualifications/c0e7730a0b884d2797db310ea4b88083/complaints/699f247a7b8b4016abd9d4b75e44b7fd/documents/da2aff1472184b28ac8b7130d5575d93?download=b1cd9c835eb6466ab5a15944307f648e", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-08T16:32:23.000808+02:00", 
          "id": "da2aff1472184b28ac8b7130d5575d93", 
          "dateModified": "2016-03-08T16:32:23.000860+02:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/ea5d68674ac847f887792dc42191b192/qualifications/c0e7730a0b884d2797db310ea4b88083/complaints/699f247a7b8b4016abd9d4b75e44b7fd/documents/86c7f0f13b904d86acc273a4fe5282c0?download=e88b58c46109495898bba65758308777", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-08T16:32:25.321143+02:00", 
          "id": "86c7f0f13b904d86acc273a4fe5282c0", 
          "dateModified": "2016-03-08T16:32:25.321181+02:00"
        }
      ], 
      "dateAccepted": "2016-03-08T16:32:24.838286+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2016-03-08T16:32:24.583266+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2016-03-08T16:32:23.646999+02:00", 
      "complaintID": "UA-2016-03-08-000001.2", 
      "date": "2016-03-08T16:32:23.645539+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "03c08d97d095484483db655bc027cb2e"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2016-03-08T16:32:25.846277+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2016-03-08T16:32:25.075269+02:00", 
      "dateSubmitted": "2016-03-08T16:32:23.855879+02:00", 
      "complaintID": "UA-2016-03-08-000001.3", 
      "date": "2016-03-08T16:32:23.854285+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "c0afec23f96b4fd0aff77e4910d84d85"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2016-03-08T16:32:24.331013+02:00", 
      "dateSubmitted": "2016-03-08T16:32:24.091417+02:00", 
      "complaintID": "UA-2016-03-08-000001.4", 
      "date": "2016-03-08T16:32:24.089989+02:00", 
      "type": "complaint", 
      "id": "cb51bbb56c2947edb1b1aa5cba901265"
    }
  ]
}

