PATCH /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2016-03-16T16:32:06.249715+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/3b95ac5554904720bed2c4fcae434d4f?download=27c6335f49434b728393acc285547a70", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:04.858556+02:00", 
        "id": "3b95ac5554904720bed2c4fcae434d4f", 
        "dateModified": "2016-03-08T16:32:04.858583+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?download=c9d88db99380423aa68ad940bbe5c824", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:05.104009+02:00", 
        "id": "797ecc3074424c8685a11c54ef8f27ad", 
        "dateModified": "2016-03-08T16:32:05.104049+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?download=ccc241fe427148c8839683f7fb6a42d3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-08T16:32:05.104009+02:00", 
        "id": "797ecc3074424c8685a11c54ef8f27ad", 
        "dateModified": "2016-03-08T16:32:05.350993+02:00"
      }
    ], 
    "tenderID": "UA-2016-03-08-000001", 
    "tenderPeriod": {
      "startDate": "2016-02-09T16:32:05.956224+02:00", 
      "endDate": "2016-03-16T16:32:06.249715+02:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "complaintPeriod": {
      "startDate": "2016-02-09T16:32:05.956224+02:00", 
      "endDate": "2016-03-12T16:32:06.249715+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-03-16T16:32:06.249715+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-03-08T16:32:05.549235+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "0122de48e04b446ea31fa6730576e595", 
        "questionOf": "tender"
      }
    ], 
    "enquiryPeriod": {
      "startDate": "2016-02-09T16:32:05.956224+02:00", 
      "endDate": "2016-03-06T16:32:06.249715+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-03-08T16:32:06.361002+02:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "06affbb4b90e482fb3163dcca47255be", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "78d669fde4a041228b824c2151085d2a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "af13521637c74f7aaf9f1d52782e99f1", 
    "awardCriteria": "lowestCost"
  }
}

