PUT /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy206078540005$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/797ecc3074424c8685a11c54ef8f27ad?download=ccc241fe427148c8839683f7fb6a42d3", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-08T16:32:05.104009+02:00", 
    "id": "797ecc3074424c8685a11c54ef8f27ad", 
    "dateModified": "2016-03-08T16:32:05.350993+02:00"
  }
}

