POST /api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents?acc_token=d93795bc346d4aa2ae9b64fbfe56e4c4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy664868586635$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/3b95ac5554904720bed2c4fcae434d4f
{
  "data": {
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/af13521637c74f7aaf9f1d52782e99f1/documents/3b95ac5554904720bed2c4fcae434d4f?download=27c6335f49434b728393acc285547a70", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-08T16:32:04.858556+02:00", 
    "id": "3b95ac5554904720bed2c4fcae434d4f", 
    "dateModified": "2016-03-08T16:32:04.858583+02:00"
  }
}

